### PR TITLE
Bug 2116416: core: add support to rotate log based on logfile size

### PR DESCRIPTION
**Pull request by subhamkrai**
this commits add new field `MaxLogSize` inside `LogCollectorSpec` of
cephCluster cr which will take max size of log after which we want to
rotate the log.

Signed-off-by: subhamkrai <srai@redhat.com>
(cherry picked from commit 62f73dcd989dde83eca48f58c47a7d27d98b6bc1)
(cherry picked from commit cb7728141fae86384d81e11297e0be2158b871fe)

core: fix logrotate bash check and periodicity logic

we need use `!=` for string comparision in bash instead of
`-ne`. Also, need to correct periodicity if condition to
make it work as expected.

Signed-off-by: subhamkrai <srai@redhat.com>
(cherry picked from commit https://github.com/red-hat-storage/rook/commit/9d4d5bc7025a026a7f11c52f48f1db0c00c4d5c9)

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
@travisn ^^^

**Comment by travisn** [comment]
@subhamkrai we are just waiting on BZ approval for 4.11

**Comment by subhamkrai** [comment]
waiting for https://github.com/rook/rook/pull/10751

**Pull request merged**
