### PR TITLE
Bug 2167516: external: add support for multisite in external cluster script

### PR DESCRIPTION
**Pull request by parth-gr**
**Description of your changes:**

1) The function is used for rbd so it should be name to validate_rbd_metadata_ec_pool_name

2) Add support for realm, zone and zonegroup

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by parth-gr** [comment]
//asign @travisn

**Review by travisn — CHANGES_REQUESTED** [review]
- This PR pulls in three commits for the external cluster changes instead of just a single commit from https://github.com/rook/rook/pull/12037. Was that intended? 
- Please add a description to the PR
- There is a merge commit in the PR that needs to be removed. We should just see cherry-picked commits.

**Comment by parth-gr** [comment]
> * This PR pulls in three commits for the external cluster changes instead of just a single commit from [external: add support for multisite in external cluster script rook/rook#12037](https://github.com/rook/rook/pull/12037). Was that intended?
> * Please add a description to the PR
> * There is a merge commit in the PR that needs to be removed. We should just see cherry-picked commits.

Yaa right, my branch was not up to date,

So for now we only need two commits:
1) name correction https://github.com/rook/rook/pull/12036

2) The original Multisite commit,

Taken first one as it was coming merge conflicts, So instead of resolving I thought would be good even we can also pick that fix.
Thanks

**Review by travisn — APPROVED** [review]

**Pull request merged**
