### PR TITLE
Added new rook bundle creation script

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
- Added Dockerfile to create rook-ceph-operator-bundle under the rook repo.
- Updated the Makefile to have the 'bundle' command, that reference the 'gen-bundle.sh' script under `build/bundle`.
- Moved the rook csv under build/csv/ceph directory to keep all the manifests at one location for bundle creation

**Checklist:**

- [X] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [X] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [X] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [X] Documentation has been updated, if necessary.
- [X] Unit tests have been added, if necessary.
- [X] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
cc @subhamkrai @iamniting

**Comment by travisn** [comment]
> IIRC, this master branch is just a resync of the master branch from github.com/rook/rook. I think these changes will be un-done the next time the branches are synced. Am I missing something? Or is there a way to make these changes to the Rook upstream as well?

The resync should just be bringing the commits from upstream to the downstream. It's not resetting the branch, so the only risk of making changes in the downstream master should be if there are merge conflicts. Also it's important to note that the downstream release branches will be created directly from the upstream branches, so any commits in the downstream master would not be included in the downstream release branches IIUC.

**Comment by Nikhil-Ladha** [comment]
> The resync should just be bringing the commits from upstream to the downstream. It's not resetting the branch, so the only risk of making changes in the downstream master should be if there are merge conflicts. Also it's important to note that the downstream release branches will be created directly from the upstream branches, so any commits in the downstream master would not be included in the downstream release branches IIUC.

The release branches created now are being synced from the downstream master only, though I guess once we have an upstream release that would be reset to an upstream release branch. So, once we get these changes into the master branch d/s, these changes would be synced to the release branch as well.

**Comment by Nikhil-Ladha** [comment]
Tested the changes and everything is working fine

**Review by iamniting — APPROVED** [review]

**Review by subhamkrai — APPROVED** [review]

**Review by sp98 — APPROVED** [review]

**Pull request merged**
