### PR TITLE
Bug 2249735: fix multus net detect job all placement

### PR DESCRIPTION
**Pull request by BlaineEXE**
Fix an issue in the network address detection job where placement was only retreived from osd and not merged with all.

Signed-off-by: Blaine Gardner <blaine.gardner@ibm.com>
(cherry picked from commit 0a538bfc37f1c6e5e5dfa6936d9297b37553201a) (cherry picked from commit d829f8c0b16b7c38ca90ca7f3d3b6785424c26f5)

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by parth-gr** [comment]
@BlaineEXE can you force push I see a lot of CI is failing

@agarwal-mudit can you do a restart?

**Comment by subhamkrai** [comment]
Couple of CI issues has been fixed in rook upstream but those are no backported to downstream 4.14 so we need those also. For example https://github.com/rook/rook/commit/345f92961b5f51e84032297a6f72b5a42dda0f4b this.

**Comment by parth-gr** [comment]
> Couple of CI issues has been fixed in rook upstream but those are no backported to downstream 4.14 so we need those also. For example [rook@345f929](https://github.com/rook/rook/commit/345f92961b5f51e84032297a6f72b5a42dda0f4b) this.

@subhamkrai I think we should include at least major one with this PR, WDYT?

**Pull request merged**
