### PR TITLE
csv: add annotation to make rook non-standalone

### PR DESCRIPTION
**Pull request by subhamkrai**
csv: add annotation to make rook non-standalone

we don't want to show rook-ceph operator as a standalone
operator in openshift installed operator list. So, adding
annotation `operators.operatorframework.io/operator-type: non-standalone`
to skip listing rook-ceph.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
@Nikhil-Ladha @iamniting ^^

**Comment by iamniting** [comment]
> We need to update the logo to Red Hat logo as well.

yes we do need to.

**Comment by subhamkrai** [comment]
> We need to update the logo to Red Hat logo as well.

done, I copied from ocs-operator

**Review by Nikhil-Ladha — APPROVED** [review]
lgtm

**Pull request merged**
