### PR TITLE
DFBUGS-979: Revert "csi: disable fencing in Rook"

### PR DESCRIPTION
**Pull request by subhamkrai**
This reverts commit 4e761bd53c25e86690088a8bfb41910b5624e4da.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
@sp98 PTAL we need to revert the fix and move to next patch release as previous patch release was cve only

**Comment by sp98** [comment]
> @sp98 PTAL we need to revert the fix and move to next patch release as previous patch release was cve only

@subhamkrai Why are you enabling it again? Please add more details about this. Also, the CI is failing.

**Comment by subhamkrai** [comment]
> > @sp98 PTAL we need to revert the fix and move to next patch release as previous patch release was cve only
> 
> @subhamkrai Why are you enabling it again? Please add more details about this. Also, the CI is failing.

CI failure is kind of not related, CI is failing at the cluster creation stage which is due to the old version.

We are reverting the changes as it merged in CVE only patch

**Comment by agarwal-mudit** [comment]
@subhamkrai is there a bug for this? please do add

**Comment by subhamkrai** [comment]
> @subhamkrai is there a bug for this? please do add

@agarwal-mudit bug is to disable the networkFence but since the changes were merged in CVE only patch we need to revert the change for now and fix in right version. So, technically no bug for this PR as it is reverting the changes only

**Comment by agarwal-mudit** [comment]
We need a bug for every change in z-stream (unless its test only change), please create one and reach out to Sunil/Karthick for approvals

**Comment by subhamkrai** [comment]
> We need a bug for every change in z-stream (unless its test only change), please create one and reach out to Sunil/Karthick for approvals

okay 👍🏽

**Pull request merged**
