### PR TITLE
Sync latest master from upstream rook

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
**Description of your changes:**
This PR syncs the latest code from upstream master to downstream master branch.

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
With the goal of having the rook CSV separated out from ocs-operator, we need to start maintaining the downstream rook repo and sync the latest commits daily from upstream repo and have the CSV generation script added here to be referenced in the ocs-operator code.
This sync can be handled by the automated pipeline that we have for csi-addons, ceph-csi and ramen.

**Comment by Nikhil-Ladha** [comment]
@subhamkrai can you please take a look at the prow/unit test failure once and see if something could be done about it?

**Comment by subhamkrai** [comment]
> @subhamkrai can you please take a look at the prow/unit test failure once and see if something could be done about it?

looking

**Comment by subhamkrai** [comment]
> @subhamkrai can you please take a look at the prow/unit test failure once and see if something could be done about it?

@Nikhil-Ladha I'm not sure about this error
```bash
ERRO[2024-02-06T14:20:58Z] Some steps failed:                           
ERRO[2024-02-06T14:20:58Z] 
  * could not run steps: step unit failed: test "unit" failed: could not watch pod: the pod ci-op-mrip83sl/unit failed after 1m10s (failed containers: test): ContainerFailed one or more containers exited
Container test exited with code 1, reason Error
---
```

I think Nitin/Malay could help with Prow issue

**Comment by Nikhil-Ladha** [comment]
I guess we should be fine to disable it, anyway I don't see this job running on release branches

**Comment by Nikhil-Ladha** [comment]
@travisn if we are good with merging this PR for now, let's merge this and I will enable the daily sync for the repo while we discuss on the csv approach on the design doc.
You might have to override the `prow` test for this PR, and I will disable it tomorrow for the master branch.

**Pull request merged**
