### PR TITLE
DFBUGS-901: ci: fix ci issue downstream

### PR DESCRIPTION
**Pull request by parth-gr**
the unit test ws failing, as in 4.16
we were setting the osd resize manually true,
So the re-weight was called twice once from the
device class update and another from osd reweight

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by BlaineEXE — APPROVED** [review]

**Comment by parth-gr** [comment]
@BlaineEXE removed the python script changes

**Comment by BlaineEXE** [comment]
/lgtm
/approve

It looks like the jira bot thinks there is still an error with the bug (jira/invalid-bug label). Not sure why exactly 

/jira refresh

**Comment by parth-gr** [comment]
@Nikhil-Ladha can you take a look

**Comment by Nikhil-Ladha** [comment]
We don't have the necessary approvals in the linked jira issue i.e, `Target Version` field is not updated with the correct value because Dev Approval and QE Approval is not set.
Please provide/get the acks and then do a `/jira refresh`. It will work.

**Pull request merged**
