### PR TITLE
csv: update csv version to 4.16

### PR DESCRIPTION
**Pull request by subhamkrai**
**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Please update the csv as well by running the `make gen-csv` cmd, as a separate commit.

**Comment by subhamkrai** [comment]
> Please update the csv as well by running the `make gen-csv` cmd, as a separate commit.

missed that, added it now. Thanks

**Review by Nikhil-Ladha — COMMENTED** [review]
/lgtm

**Review by Nikhil-Ladha — APPROVED** [review]

**Pull request merged**
