### PR TITLE
Bug 2245978: multus: use rook image for ip range detection

### PR DESCRIPTION
**Pull request by BlaineEXE**
Use the Rook image (defined by the operator pod) to detect the Multus network address ranges. It is reasonable for users to want to have a minimal Ceph image that does not have the `ip` utility installed, which is used for detecting the address ranges of multus interfaces. Instead, use the Rook image, which Rook can ensure has the `ip` tool if Ceph ever removes it from their image.

Signed-off-by: Blaine Gardner <blaine.gardner@ibm.com>
(cherry picked from commit 8aec30aa5a22a4051db01b4b182fa67a9e2c3960)

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by travisn** [comment]
Looks good, assuming we get the ip tool in the base image downstream.
/lgtm
/approve

**Comment by BlaineEXE** [comment]
Correction @travisn: This PR means that ODF needs to get the `ip` tool into the Rook image, and would make it so we do _not_ need it in the base image.

**Comment by travisn** [comment]
> Correction @travisn: This PR means that ODF needs to get the `ip` tool into the Rook image, and would make it so we do _not_ need it in the base (RHCS) image. Unless I'm misunderstanding the base image used for ODF-Rook.

Oh right, in the downstream rook image is what I meant, thanks.

**Comment by travisn** [comment]
What if we also cherry-pick some recent CI fixes with this?
https://github.com/rook/rook/pull/13128
https://github.com/rook/rook/pull/13057
https://github.com/rook/rook/pull/13105

**Comment by BlaineEXE** [comment]
> What if we also cherry-pick some recent CI fixes with this? [rook#13128](https://github.com/rook/rook/pull/13128) [rook#13057](https://github.com/rook/rook/pull/13057) [rook#13105](https://github.com/rook/rook/pull/13105)

Done. Each is a separate cherry-pick commit.

**Pull request merged**
