### PR TITLE
Syncing latest changes from master for rook

### PR DESCRIPTION
**Pull request by df-build-team**
PR containing the latest commits from master branch

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha Please check why auto-generated PR is adding csv changes https://github.com/red-hat-storage/rook/actions/runs/11285096924/job/31387343578?pr=750

I see this PR #748 was merged without commiting the gen-csv changes. The actuon was failung for that PR and we still merged that, why @parth-gr @travisn ?
The release branch sync pipeline is not responsible for commiting the csv changes if they are not present in master.

**Comment by parth-gr** [comment]
@Nikhil-Ladha missed checking if Linux build was failing because of it, wasn't sure if changing the python script would have impacted the csv, it was not before like this,
I can open a separate PR to fix this, till then we can hold this PR

Thanks for notifying it:)

**Comment by parth-gr** [comment]
@Nikhil-Ladha we have the changes by Jenkins yesterday https://github.com/red-hat-storage/rook/pull/751/commits/7370faab8e0bbdc49c4be688e25fb816b2abd80c

**Comment by parth-gr** [comment]
@mergifyio rebase

**Comment by Nikhil-Ladha** [comment]
> @Mergifyio rebase

No, we shouldn't be doing this.
Only when we have a stable build, the commits will be added to this PR by the pipeline.

**Comment by subhamkrai** [comment]
@Nikhil-Ladha should I raise manual PR to add csv changes in 4.18 and then this will be fixed or what is the solution?

**Comment by Nikhil-Ladha** [comment]
Let's wait for the next stable build to happen so that we have the latest commits from the master branch, considering we have the csv changes because of the u/s to d/s sync pipeline in the master branch already.

**Comment by subhamkrai** [comment]
> Let's wait for the next stable build to happen so that we have the latest commits from the master branch, considering we have the csv changes because of the u/s to d/s sync pipeline in the master branch already.

Next stable build make the the CI green

**Comment by subhamkrai** [comment]
> > Let's wait for the next stable build to happen so that we have the latest commits from the master branch, considering we have the csv changes because of the u/s to d/s sync pipeline in the master branch already.
> 
> Next stable build make the the CI green

The RGW failure is know but anyways I reran to see if that makes it green that otherwise I'll merge this

**Pull request merged**
