### PR TITLE
Bug 2236444: monitoring: set port for servicemonitor for ceph-exporter

### PR DESCRIPTION
**Pull request by weirdwiz**
This commit makes the port name configurable to set the port name of the service monitor.

### CODE REVIEW

**Comment by subhamkrai** [comment]
@weirdwiz is this already fixed in the upstream project? we first need to fix it rook/rook upstream project and then we cherry-pick.

**Comment by weirdwiz** [comment]
@subhamkrai updated the commit for the chery-pick
ptal

**Comment by subhamkrai** [comment]
@travisn ^^

**Pull request merged**
