### PR TITLE
Bug 2069314: csi: make storage class updated with csi-users in external cluster

### PR DESCRIPTION
**Pull request by parth-gr**
**Description of your changes:**

For using restricted auth users we need to update the
restricted users in the Storage class, so updating
it in the json output for external cluster

Signed-off-by: parth-gr <paarora@redhat.com>

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by parth-gr** [comment]
> Shall we also backport this on top of the `black` formatting changes from [rook#10399](https://github.com/rook/rook/pull/10399) so we don't have merge conflicts in the future backports?

Okay yes, checking with Subham

**Comment by subhamkrai** [comment]
> Shall we also backport this on top of the `black` formatting changes from [rook#10399](https://github.com/rook/rook/pull/10399) so we don't have merge conflicts in the future backports?

can we bp `black` changes to 4.11 without black?

**Comment by agarwal-mudit** [comment]
@subhamkrai Lets raise a BZ, its just formatting changes, I can ask QE to ack it based on regression.
/bugzilla refresh
/hold

**Comment by subhamkrai** [comment]
> @subhamkrai Lets raise a BZ, its just formatting changes, I can ask QE to ack it based on regression. /bugzilla refresh /hold

Thanks @agarwal-mudit, I'll raise the bz and create the BP pr

**Review by agarwal-mudit — APPROVED** [review]
/lgtm

**Pull request merged**
