### PR TITLE
 Bug 2187952: Disable exporter service for downstream 4.13

### PR DESCRIPTION
**Pull request by avanthakkar**
Signed-off-by: avanthakkar <avanjohn@gmail.com>

**Description of your changes:**
Create the exporter service only if exporter pods are created.

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by travisn** [comment]
If we go ahead with this, will need to update to match the upstream PR https://github.com/rook/rook/pull/12118

**Comment by avanthakkar** [comment]
> If we go ahead with this, will need to update to match the upstream PR [rook#12118](https://github.com/rook/rook/pull/12118)

Yes, will update version to `18.0.0` here as well!

**Review by subhamkrai — APPROVED** [review]
LGTM

**Comment by subhamkrai** [comment]
@agarwal-mudit @travisn  ^^

**Pull request merged**
