### PR TITLE
Bug 2089137: external: fix import errors for python2

### PR DESCRIPTION
**Pull request by parth-gr**
remove duplicate import urllib.parse which is handled below with try and except no need to import separately. Also, change the way to get the python version.

(cherry picked from commit 9a952df419f8d9273e695bff3557986f82e6e166)

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by parth-gr** [comment]
//assign @subhamkrai

**Comment by travisn** [comment]
@agarwal-mudit Do we need this BZ to be acked again, or when can we merge this fix?
https://bugzilla.redhat.com/show_bug.cgi?id=2089137

**Comment by agarwal-mudit** [comment]
> https://bugzilla.redhat.com/show_bug.cgi?id=2089137

Yes, we need to ack it again for 4.11.8 and wait for the branch to open for 4.11.8

**Comment by travisn** [comment]
Closed as won't fix

**Pull request closed without merging**
