### PR TITLE
Bug 2239802: external: update healthchecker caps for rbd command

### PR DESCRIPTION
**Pull request by subhamkrai**
when creating networkFence CR, it requires IP's to block which we get from running `rbd status ...` command. But, the client.healthchecker user didn't had the right caps to run hence it was giving error. Now, adding the required caps `profile rbd-read-only` to osd so that rbd command can be executed.

(cherry picked from commit c78bd1cbc61b885ae4a2385ec6432b121dd21f1c) (cherry picked from commit 9ac3442847f2c31bb71ff842c1636dcc25687eb5)

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
@travisn @parth-gr ^^ there was some conflicts in the docs regarding `--cluster-name` with `--k8s-cluster-name`.

**Comment by travisn** [comment]
> @travisn @parth-gr ^^ there was some conflicts in the docs regarding `--cluster-name` with `--k8s-cluster-name`.

@parth-gr Was that rename also intended to be in 4.14? Or it can wait for 4.15?

@subhamkrai Please also cherry-pick the CI fixes for the disk cleanup action in this PR so we can fix the downstream CI at the same time.

**Comment by subhamkrai** [comment]
@travisn ready to merge

**Pull request merged**
