### PR TITLE
Bug 2141947: object: mark endpoint as a optional field

### PR DESCRIPTION
**Pull request by iamniting**
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2141947

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by iamniting** [comment]
@travisn @BlaineEXE Can you pls take a look?

**Comment by parth-gr** [comment]
/approve
Looks good to me to make the endpoint optional, 

I think we should also make this change upstream to make this change consistent.

**Comment by iamniting** [comment]
> /approve Looks good to me to make the endpoint optional,
> 
> I think we should also make this change upstream to make this change consistent.

It is already available in the upstream

**Comment by subhamkrai** [comment]
> > /approve Looks good to me to make the endpoint optional,
> > I think we should also make this change upstream to make this change consistent.
> 
> It is already available in the upstream

Right, the changes are already in upstream master, somehow we missed in downstream cherry-pick.

**Comment by subhamkrai** [comment]
> > > /approve Looks good to me to make the endpoint optional,
> > > I think we should also make this change upstream to make this change consistent.
> > 
> > 
> > It is already available in the upstream
> 
> Right, the changes are already in upstream master, somehow we missed in downstream cherry-pick.

@iamniting these changes also need in upstream 1.10 branch but not in master

**Comment by iamniting** [comment]
> > > > /approve Looks good to me to make the endpoint optional,
> > > > I think we should also make this change upstream to make this change consistent.
> > > 
> > > 
> > > It is already available in the upstream
> > 
> > 
> > Right, the changes are already in upstream master, somehow we missed in downstream cherry-pick.
> 
> @iamniting these changes also need in upstream 1.10 branch but not in master

I see here is a PR https://github.com/rook/rook/pull/11300

**Pull request merged**
