### PR TITLE
Bug 2006323: [release-4.8] adding 'namespace' field to the needed ceph queries

### PR DESCRIPTION
**Pull request by aruniiird**
Signed-off-by: Arun Kumar Mohan <amohan@redhat.com>
(cherry picked from commit 8950e78a4f9a15669fee50699647cc6249068322)

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
/retitle Bug 2006323: [release-4.8] ceph: adding 'namespace' field to the needed ceph queries

**Comment by aruniiird** [comment]
Following error happened in integration tests,
```
2021-10-01 12:43:45.519129 I | integrationTest: pool upgradepool still exists
2021-10-01 12:43:50.520073 D | exec: Running command: kubectl exec -i rook-ceph-tools-78cdfd976c-knwfd -n upgrade-ns -- timeout 15 ceph osd lspools --connect-timeout=15 --format json
2021-10-01 12:43:50.616394 W | integrationTest: error getting pools. failed to list pools: exit status 1
failed to list pools
```
They don't seem to be related to this change.

**Review by travisn — APPROVED** [review]
The CI issues are not related to this change, let's go ahead and merge.

**Pull request merged**
