### PR TITLE
Manual sync upstream master to downstream master

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
This is a manual sync PR from upstream to downstream master

### CODE REVIEW

**Review by subhamkrai — CHANGES_REQUESTED** [review]
@Nikhil-Ladha needs to run `make gen-csv` to get CI green

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha needs to run `make gen-csv` to get CI green

Done

**Review by subhamkrai — APPROVED** [review]

**Pull request merged**
