### PR TITLE
Bug 2005515: Add timeout in mgr init container

### PR DESCRIPTION
**Pull request by travisn**
**Description of your changes:**
The mgr init containers run a ceph command that may get stuck if the mon quorum is down. The liveness probe is not in effect during the init containers, thus the mgr pod may stay hung indefinitely when this happens. To ensure the mgr does not hang, we add a bash timeout to the ceph command so it will restart and try again in case mon quorum is restored.

**Which issue is resolved by this Pull Request:**
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2005515

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

### CODE REVIEW

**Review by leseb — CHANGES_REQUESTED** [review]
https://github.com/openshift/rook/pull/289/files#r711923289

**Review by leseb — APPROVED** [review]

**Comment by agarwal-mudit** [comment]
@travisn We are good for merging this.

**Pull request merged**
