### PR TITLE
ci: stop running ci concurrently when pr is fresh

### PR DESCRIPTION
**Pull request by subhamkrai**
Signed-off-by: subhamkrai <srai@redhat.com>
(cherry picked from commit 41f36ff9dff7dfb92e447f685d28442d58ac5dbf)

backport of https://github.com/red-hat-storage/rook/pull/462

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by parth-gr** [comment]
Why it is not open for upstream CI?
We can avoid the same problem ther, right?

**Review by Madhu-1 — APPROVED** [review]

**Comment by Madhu-1** [comment]
> > Why it is not open for upstream CI? We can avoid the same problem there, right?
> 
> for upstream, we have the same setting for canary test, but we don't have for the integration test since for upstream we don't have a resource limit. We can run 60 runners parallelly but downstream I guess it 15 or 20 not sure but very less. That's why.

it doesn't matter if its upstream/downstream its good to stop the ongoing Jobs when PR is updated, if the changes are not present in upstream add it to upstream and backport it to downstream

**Comment by subhamkrai** [comment]
Closing this pr, since will create upstream pr first and then backport those to downstream.

**Comment by subhamkrai** [comment]
Reopening since upstream pr is not required since we are not releasing upstream 1.8 and 1.9.

**Comment by travisn** [comment]
Not waiting for the CI to complete since it will anyway fail until the next CI PR.

**Pull request merged**
