### PR TITLE
Bug 2190145: security: update vault to 1.13.1

### PR DESCRIPTION
**Pull request by subhamkrai**
**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/latest/Contributing/development-flow/#commit-structure)).
- [ ] **Skip Tests for Docs**: If this is only a documentation change, add the label `skip-ci` on the PR.
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/latest/Contributing/development-flow/#submitting-a-pull-request)
- [ ] [Pending release notes](https://github.com/rook/rook/blob/master/PendingReleaseNotes.md) updated with breaking and/or notable changes for the next minor release.
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Comment by subhamkrai** [comment]
The tests are failing due to, vault 1.13.1 requiring golang 1.19.

**Comment by subhamkrai** [comment]
@travisn if this looks good, I can create similar PR's for older versions

**Comment by travisn** [comment]
added the do-not-merge flag until we can confirm if a newer golang can be used, otherwise we need to close this

**Comment by subhamkrai** [comment]
> added the do-not-merge flag until we can confirm if a newer golang can be used, otherwise we need to close this

A newer version of golang, can't be used in the z stream. so closing this one

**Pull request closed without merging**
